### ISSUE TITLE
Missing MMSE_baseline Function

### ISSUE THREAD

**Issue by sasfkjiaw** [ROCASSO/MI-based-WMMSE-ISAC-algorithm#1]
I am currently conducting research in this area as well. While attempting to reproduce your code, I found that the _MMSE_baseline_ function seems to be missing. It might also be a problem occurring during my run qwq. By the way, it seems the Sensing_beam_pattern file is also missing a _.m_ extension.

**Comment by ROCASSO** [comment]
qwq

**Comment by ROCASSO** [comment]
pls find the original paper  "A robust interference alignment algorithm in a MIMO interference channel" for information about the baseline. I accidentally put the code into trash bin when i am cleaning my PC few weeks ago....... sorry about that. What u mean by QWQ BTW?

**Comment by sasfkjiaw** [comment]
qwq is just a chat term, similar to :). I accidentally included it. Thank you very much for your reply! I will further study the code and the article in more detail later.

**Comment by ROCASSO** [comment]
Understood QWQ, pls dont hesitate to contact us if you have any question. I got the meaning of QWQ now, cute emoji.

**Comment by sasfkjiaw** [comment]
> 了解QWQ，如果您有任何问题，请随时与我们联系。我现在明白了QWQ的意思，可爱的表情符号。

Thank you for your understanding and for acknowledging the QWQ emoji .
I appreciate your offer to help. I will reach out if I encounter any further issues or have additional questions.
